// Run against tests.browser_fixture on localhost; all providers are fictional.
async (page) => {
  const assert=(condition,message)=>{if(!condition)throw new Error(message);};
  const errors=[],requests=[];
  page.on('pageerror',error=>errors.push(error.message));
  page.on('request',request=>requests.push(request.url()));
  await page.unroute('**/api/**');
  await page.unroute('**/api/calls');
  await page.setViewportSize({width:1440,height:1000});
  await page.goto('http://127.0.0.1:8765/?book=stay&room=spa-suite');
  await page.locator('#token').fill('fixture-operator');
  await page.locator('#connect').click();
  await page.waitForFunction(()=>state.connected && bookingUi.services.length && bookingUi.roomTypes.length);
  assert(await page.locator('#new-room-type').inputValue()==='spa-suite','hotel link lost selected room');
  await page.locator('#booking-kind-slot').click();
  const date=await page.evaluate(()=>{let date=dayAfter(tallinnDay());while([0,6].includes(new Date(date+'T12:00:00Z').getUTCDay()))date=dayAfter(date);return date;});
  await page.locator('#new-service').selectOption('1');
  await page.locator('#new-slot-date').fill(date);
  await page.locator('#booking-search').click();
  await page.waitForFunction(()=>!bookingUi.busy);
  assert(await page.locator('.offer-button').count()>0,'spa availability missing');
  await page.locator('.offer-button').first().click();
  await page.waitForFunction(()=>!bookingUi.busy);
  assert(await page.locator('#booking-confirm').isDisabled(),'rendering opened consent before deliberate reading');
  assert((await page.locator('#booking-recap-text').textContent()).includes('Fiktiivne'),'spa recap lacks disclosure');
  assert(await page.locator('#bookings tbody tr').count()===0,'prepare created a booking before consent');
  await page.locator('#booking-recap-read').click();
  await page.waitForFunction(()=>!bookingUi.busy);
  assert(await page.locator('#booking-confirm').isEnabled(),'deliberate reading did not open separate confirmation');
  assert(await page.locator('#bookings tbody tr').count()===0,'reading created a booking before consent');
  await page.locator('#booking-decline').click();
  assert(await page.locator('#bookings tbody tr').count()===0,'decline created a booking');
  await page.locator('#booking-search').click();
  await page.waitForFunction(()=>!bookingUi.busy);
  await page.locator('.offer-button').last().click();
  await page.waitForFunction(()=>!bookingUi.busy);
  await page.locator('#booking-recap-read').click();
  await page.waitForFunction(()=>!bookingUi.busy);
  await page.locator('#booking-confirm').click();
  await page.waitForFunction(()=>!bookingUi.busy && document.querySelectorAll('#bookings tbody tr').length===1);
  assert(await page.locator('#bookings tbody tr').count()===1,'confirmed spa booking missing');
  const spaReceipt=await page.locator('#booking-receipt-text').textContent();
  await page.locator('#booking-cancel-request').click();
  await page.locator('#booking-cancel').click();
  await page.waitForFunction(()=>!bookingUi.busy && !state.readBusy && document.querySelectorAll('#bookings tbody tr').length===0);
  assert(await page.locator('#bookings tbody tr').count()===0,'cancelled spa booking still active');
  await page.locator('#booking-kind-stay').click();
  await page.locator('#new-room-type').selectOption('');
  await page.locator('#new-checkin').fill(date);
  await page.locator('#new-checkout').fill(await page.evaluate(date=>dayAfter(date,2),date));
  await page.locator('#booking-search').click();
  await page.waitForFunction(()=>!bookingUi.busy);
  assert(await page.locator('.offer-button').count()===3,'room offers missing');
  await page.locator('.offer-button').first().click();
  await page.waitForFunction(()=>!bookingUi.busy);
  assert((await page.locator('#booking-recap-text').textContent()).includes('Näidishind'),'room recap lost synthetic price label');
  assert(await page.locator('.stay-row').count()===0,'room booked before consent');
  assert(await page.locator('#booking-confirm').isDisabled(),'room recap rendering opened consent');
  await page.locator('#booking-recap-read').click();
  await page.waitForFunction(()=>!bookingUi.busy);
  await page.locator('#booking-confirm').click();
  await page.waitForFunction(()=>!bookingUi.busy && document.querySelectorAll('.stay-row').length===1);
  assert(await page.locator('.stay-row').count()===1,'confirmed room missing');
  const roomReceipt=await page.locator('#booking-receipt-text').textContent();
  // A fresh session cannot cancel the first session's receipt.
  const crossSession=await page.evaluate(async()=>{
    const headers={'Content-Type':'application/json','Authorization':'Bearer fixture-operator'};
    const session=await fetch('/api/booking/session',{method:'POST',headers,body:'{}'}).then(response=>response.json());
    const response=await fetch('/api/booking/cancel',{method:'POST',headers,body:JSON.stringify({session_id:session.session_id,kind:'stay',booking_id:bookingUi.confirmed.id,consent:true})});
    await fetch('/api/demo/session/'+session.session_id,{method:'DELETE',headers});
    return response.status;
  });
  assert(crossSession===409,'another session cancelled an owned stay');
  const layouts=[];
  for(const width of [1440,1024,768,700,390,320]){
    await page.setViewportSize({width,height:900});
    const size=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));
    assert(size.scroll<=size.width,'dashboard overflow: '+JSON.stringify(size));layouts.push(size);
  }
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:'output/playwright/booking-connected-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'output/playwright/booking-connected-mobile.png',fullPage:true});
  await page.locator('#booking-cancel-request').click();
  await page.locator('#booking-cancel').click();
  await page.waitForFunction(()=>!bookingUi.busy && !bookingUi.staysBusy && document.querySelectorAll('.stay-row').length===0);
  assert(await page.locator('.stay-row').count()===0,'cancelled room still counted as active');
  assert(await page.locator('#overview-stays').textContent()==='0','cancelled room remained in overview');
  // Inject a lost write receipt and ensure the UI never repeats the write.
  await page.locator('#booking-kind-slot').click();
  await page.locator('#booking-search').click();
  await page.waitForFunction(()=>!bookingUi.busy);
  await page.locator('.offer-button').first().click();
  await page.waitForFunction(()=>!bookingUi.busy);
  await page.locator('#booking-recap-read').click();
  await page.waitForFunction(()=>!bookingUi.busy);
  let uncertainWrites=0;
  await page.route('**/api/booking/confirm',route=>{uncertainWrites++;return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'write_outcome_unknown'})});});
  await page.locator('#booking-confirm').click();
  await page.waitForFunction(()=>!bookingUi.busy);
  assert(await page.locator('#booking-confirm').isDisabled(),'uncertain write left repeat confirmation open');
  assert(await page.locator('#booking-search').isDisabled(),'uncertain write allowed another booking');
  assert(uncertainWrites===1,'uncertain write was repeated');
  await page.unroute('**/api/booking/confirm');
  await page.locator('#demo-start').click();
  await page.waitForFunction(()=>!!state.sessionId);
  await page.locator('#demo-text').fill('Tere!');
  await page.locator('#demo-send').click();
  await page.waitForFunction(()=>!state.turnBusy);
  assert(await page.locator('#demo-messages li').count()===3,'text turn reply missing');
  assert(await page.locator('#demo-audio').isVisible(),'text reply audio missing');
  // Feed deterministic local audio to the microphone controller; no device used.
  await page.evaluate(()=>{
    window.fixtureCaptureContext=new AudioContext();
    const source=fixtureCaptureContext.createOscillator(),destination=fixtureCaptureContext.createMediaStreamDestination();
    source.frequency.value=330;source.connect(destination);source.start();
    navigator.mediaDevices.getUserMedia=async()=>destination.stream;
  });
  await page.locator('#demo-mic').click();
  await page.waitForFunction(()=>!!state.mic && state.mic.frames>10000);
  await page.locator('#demo-mic').click();
  await page.waitForFunction(()=>!state.micStarting && !state.turnBusy);
  await page.waitForFunction(()=>document.getElementById('demo-audio').readyState===4);
  assert(await page.locator('#demo-messages li').count()===5,'microphone reply missing');
  assert(await page.locator('#demo-audio').evaluate(element=>element.duration>0),'reply audio did not decode');
  await page.evaluate(()=>fixtureCaptureContext.close());
  await page.locator('#demo-end').click();
  await page.waitForFunction(()=>!state.sessionId);
  assert(await page.evaluate(()=>state.mic===null && state.audioUrl===null),'end conversation leaked microphone or audio');
  await page.locator('#logout').click();
  assert(await page.locator('#stays-list').textContent()==='','logout retained room data');
  assert(await page.locator('#booking-receipt').isHidden(),'logout retained booking receipt');
  assert(requests.every(url=>new URL(url).origin==='http://127.0.0.1:8765'),'browser contacted an external service');
  assert(errors.length===0,'browser errors: '+errors.join('; '));
  return {result:'passed',spaReceipt,roomReceipt,crossSession,layouts,syntheticAudio:true,uncertainWrites,errors};
}
