// Run against tests.browser_fixture on localhost; all providers are fictional.
async (page) => {
  const assert=(condition,message)=>{if(!condition)throw new Error(message);};
  const errors=[],requests=[],posts=[];
  page.on('pageerror',error=>errors.push(error.message));
  page.on('request',request=>{requests.push(request.url());if(request.method()==='POST' && new URL(request.url()).pathname.startsWith('/api/booking/'))posts.push({path:new URL(request.url()).pathname,body:request.postDataJSON()});});
  await page.unroute('**/api/**');
  await page.unroute('**/api/calls');
  await page.setViewportSize({width:1440,height:1000});
  await page.goto('http://127.0.0.1:8765/?book=table',{waitUntil:'networkidle'});
  await page.locator('#token').fill('fixture-operator');
  await page.locator('#connect').click();
  await page.waitForFunction(()=>state.connected && bookingUi.tables.length===5 && !state.readBusy);
  assert(await page.evaluate(()=>bookingUi.kind==='table'),'active composer is not restaurant-only');
  assert(await page.locator('#booking-kind-slot, #booking-kind-stay, input[type=email], input[type=tel]').count()===0,'legacy or customer-contact inputs remain active');
  const date=await page.evaluate(()=>dayAfter(tallinnDay()));
  await page.locator('#new-table-date').fill(date);
  await page.locator('#new-start-time').fill('18:00');
  await page.locator('#new-party-size').fill('3');
  await page.locator('#booking-search').click();
  await page.waitForFunction(()=>!bookingUi.busy);
  assert(await page.locator('.offer-button').count()===1,'exact table availability missing');
  const searched=posts.find(item=>item.path==='/api/booking/search').body;
  assert(searched.kind==='table' && searched.date===date && searched.start_time==='18:00' && searched.party_size===3,'table search changed the requested details');
  const preparedResponse=page.waitForResponse(response=>response.url().endsWith('/api/booking/prepare'));
  await page.locator('.offer-button').first().click();
  await page.waitForFunction(()=>!bookingUi.busy);
  const prepared=await (await preparedResponse).json();
  assert(await page.locator('#booking-confirm').isDisabled(),'preparation acknowledged an unread recap');
  assert(await page.locator('#booking-recap-read').evaluate(element=>element===document.activeElement),'preparation did not focus the reading action');
  assert((await page.locator('#booking-recap-text').textContent())===prepared.recap_text,'client rewrote the canonical table recap');
  assert((await page.locator('#booking-recap-text').textContent()).includes('Demo Esimene'),'table recap lacks the approved fictional guest');
  assert(!posts.some(item=>item.path==='/api/booking/recap'),'preparation auto-acknowledged reading');
  assert(await page.locator('#bookings tbody tr').count()===0,'prepare created a booking before consent');
  await page.locator('#booking-decline').click();
  assert(await page.locator('#bookings tbody tr').count()===0,'decline created a booking');
  await page.locator('#booking-search').click();
  await page.waitForFunction(()=>!bookingUi.busy);
  await page.locator('.offer-button').last().click();
  await page.waitForFunction(()=>!bookingUi.busy);
  // Re-preparation can retain the same hold while replacing its one-use receipt.
  // The stale UI must not authorize that replacement using a hold id alone.
  const stalePreparation=await page.evaluate(async()=>{
    const prior={hold_id:bookingUi.holdId,recap_delivery_id:bookingUi.recapDeliveryId};
    const response=await fetch('/api/booking/prepare',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer fixture-operator'},body:JSON.stringify({session_id:bookingUi.sessionId,kind:'table',table_offer_id:bookingUi.selected.table_offer_id,guest_fixture_id:'guest-001'})});
    return {status:response.status,prior,replacement:await response.json()};
  });
  assert(stalePreparation.status===200 && stalePreparation.prior.hold_id===stalePreparation.replacement.hold_id,'same-hold replacement did not exercise the real adapter');
  assert(stalePreparation.prior.recap_delivery_id!==stalePreparation.replacement.recap_delivery_id,'re-preparation reused an old receipt');
  await page.locator('#booking-recap-read').click();
  await page.waitForFunction(()=>!bookingUi.busy);
  assert(await page.evaluate(()=>!bookingUi.acknowledged && !bookingUi.recapDeliveryId),'stale receipt was acknowledged or left retryable');
  assert(await page.locator('#booking-confirm').isDisabled(),'stale same-hold acknowledgement opened confirmation');
  assert((await page.locator('#new-booking-status').textContent()).includes('Kinnitamine jääb suletuks'),'stale recap failure lacked recovery guidance');
  assert(!posts.some(item=>item.path==='/api/booking/confirm'),'stale recap triggered a confirmation');
  await page.locator('.offer-button').last().click();
  await page.waitForFunction(()=>!bookingUi.busy);
  const recapIdentity=await page.evaluate(()=>({session_id:bookingUi.sessionId,hold_id:bookingUi.holdId,recap_delivery_id:bookingUi.recapDeliveryId}));
  await page.locator('#booking-recap-read').click();
  await page.waitForFunction(()=>!bookingUi.busy && bookingUi.acknowledged);
  assert(JSON.stringify(posts.filter(item=>item.path==='/api/booking/recap').at(-1).body)===JSON.stringify(recapIdentity),'recap acknowledgement omitted the exact one-use preparation receipt');
  assert(posts.filter(item=>item.path==='/api/booking/recap').length===2,'recap acknowledgement repeated');
  assert(await page.locator('#booking-confirm').evaluate(element=>element===document.activeElement),'reading hid focus instead of moving it to explicit confirmation');
  assert(await page.locator('#bookings tbody tr').count()===0,'reading recap created a reservation');
  await page.locator('#booking-confirm').click();
  await page.waitForFunction(()=>!bookingUi.busy);
  assert(await page.locator('#bookings tbody tr').count()===1,'confirmed table booking missing');
  assert(await page.locator('#booking-receipt-title').evaluate(element=>element===document.activeElement),'confirmation did not focus its receipt');
  const tableReceipt=await page.locator('#booking-receipt-text').textContent();
  const ownedId=await page.evaluate(()=>bookingUi.confirmed.id);
  assert(/^table_[a-f0-9]{32}$/.test(ownedId),'receipt was not an authoritative table identifier');
  assert((await page.locator('#bookings tbody tr').textContent()).includes(ownedId),'independent readback lost the actual receipt');
  assert(await page.locator('#bookings tbody tr.highlight').count()===1,'receipt was not linked to independent readback');
  assert(posts.find(item=>item.path==='/api/booking/confirm').body.consent===true,'confirmation omitted explicit consent');
  // A fresh session cannot cancel the first session's receipt.
  const crossSession=await page.evaluate(async()=>{
    const headers={'Content-Type':'application/json','Authorization':'Bearer fixture-operator'};
    const session=await fetch('/api/booking/session',{method:'POST',headers,body:'{}'}).then(response=>response.json());
    const response=await fetch('/api/booking/cancel',{method:'POST',headers,body:JSON.stringify({session_id:session.session_id,kind:'table',booking_id:bookingUi.confirmed.id,consent:true})});
    await fetch('/api/demo/session/'+session.session_id,{method:'DELETE',headers});
    return response.status;
  });
  assert(crossSession===409,'another session cancelled an owned table');
  const layouts=[];
  for(const width of [1440,1024,768,700,390,320]){
    await page.setViewportSize({width,height:900});
    const size=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));
    assert(size.scroll<=size.width,'dashboard overflow: '+JSON.stringify(size));layouts.push(size);
  }
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:'output/playwright/booking-connected-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'output/playwright/booking-connected-mobile.png',fullPage:true});
  await page.locator('#booking-cancel-request').click();
  assert(!posts.some(item=>item.path==='/api/booking/cancel' && item.body.session_id===recapIdentity.session_id),'cancel request itself performed a cancellation');
  await page.locator('#booking-cancel-decline').click();
  assert(await page.locator('#booking-cancel-actions').isHidden(),'keeping the booking left cancellation active');
  assert(await page.locator('#overview-tables').textContent()==='1','cancellation decline changed the confirmed count');
  await page.locator('#booking-cancel-request').click();
  await page.locator('#booking-cancel').click();
  await page.waitForFunction(()=>!bookingUi.busy);
  assert((await page.locator('#bookings tbody tr').textContent()).includes('cancelled'),'independent readback did not show the actual cancellation status');
  assert(await page.locator('#overview-tables').textContent()==='0','cancelled table remained active in overview');
  const cancelled=posts.find(item=>item.path==='/api/booking/cancel' && item.body.session_id===recapIdentity.session_id).body;
  assert(cancelled.kind==='table' && cancelled.booking_id===ownedId && cancelled.consent===true,'cancellation did not use the owned receipt and explicit consent');
  // Inject a lost write receipt and ensure the UI never repeats the write.
  await page.locator('#new-party-size').fill('2');
  await page.locator('#booking-search').click();
  await page.waitForFunction(()=>!bookingUi.busy);
  await page.locator('.offer-button').first().click();
  await page.waitForFunction(()=>!bookingUi.busy);
  await page.locator('#booking-recap-read').click();
  await page.waitForFunction(()=>!bookingUi.busy && bookingUi.acknowledged);
  let uncertainWrites=0;
  await page.route('**/api/booking/confirm',async route=>{uncertainWrites++;const actual=await route.fetch();assert(actual.status()===200,'synthetic uncertain write never reached the actual table adapter');return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'write_outcome_unknown'})});});
  await page.locator('#booking-confirm').click();
  await page.waitForFunction(()=>!bookingUi.busy);
  assert(await page.locator('#booking-confirm').isDisabled(),'uncertain write left repeat confirmation open');
  assert(await page.locator('#booking-search').isDisabled(),'uncertain write allowed another booking');
  assert(uncertainWrites===1,'uncertain write was repeated');
  await page.locator('#refresh').click();
  await page.waitForFunction(()=>!state.readBusy && state.bookings.some(item=>item.status==='confirmed'));
  assert(await page.locator('#booking-search').isDisabled(),'independent readback silently released uncertain-write lockout');
  assert(await page.locator('#overview-tables').textContent()==='1','independent readback did not find the write whose receipt was lost');
  await page.unroute('**/api/booking/confirm');
  await page.locator('#demo-start').click();
  await page.waitForFunction(()=>!!state.sessionId);
  await page.locator('#demo-text').fill('Tere!');
  await page.locator('#demo-send').click();
  await page.waitForFunction(()=>!state.turnBusy);
  assert(await page.locator('#demo-messages li').count()===3,'text turn reply missing');
  assert(await page.locator('#demo-audio').isVisible(),'text reply audio missing');
  // Feed deterministic local audio to the microphone controller; no device used.
  await page.evaluate(()=>{
    window.fixtureCaptureContext=new AudioContext();
    const source=fixtureCaptureContext.createOscillator(),destination=fixtureCaptureContext.createMediaStreamDestination();
    source.frequency.value=330;source.connect(destination);source.start();
    navigator.mediaDevices.getUserMedia=async()=>destination.stream;
  });
  await page.locator('#demo-mic').click();
  await page.waitForFunction(()=>!!state.mic && state.mic.frames>10000);
  await page.locator('#demo-mic').click();
  await page.waitForFunction(()=>!state.micStarting && !state.turnBusy);
  await page.waitForFunction(()=>document.getElementById('demo-audio').readyState===4);
  assert(await page.locator('#demo-messages li').count()===5,'microphone reply missing');
  assert(await page.locator('#demo-audio').evaluate(element=>element.duration>0),'reply audio did not decode');
  await page.evaluate(()=>fixtureCaptureContext.close());
  await page.locator('#demo-end').click();
  await page.waitForFunction(()=>!state.sessionId);
  assert(await page.evaluate(()=>state.mic===null && state.audioUrl===null),'end conversation leaked microphone or audio');
  await page.locator('#logout').click();
  assert(await page.locator('#bookings tbody tr').count()===0,'logout retained table data');
  assert(await page.locator('#booking-receipt').isHidden(),'logout retained booking receipt');
  assert(requests.every(url=>new URL(url).origin==='http://127.0.0.1:8765'),'browser contacted an external service');
  assert(errors.length===0,'browser errors: '+errors.join('; '));
  return {result:'passed',tableReceipt,crossSession,layouts,sameHoldStaleReceiptDenied:true,syntheticAudio:true,uncertainWrites,errors};
}
